### ISSUE TITLE
Messaggio Nessun risultato trovato nella lista parcheggi

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.viaggia#11]
Test su tablet lenovo A8 - android 4.4.2

Se accedo alla schermata della lista parcheggi mi viene presentato un messaggio
"Nessun risultato trovato" mentre si sta effettuando il loading della lista.

**Comment by paolaR** [comment]
Mostrare "nessun parcheggio trovato" solo se davvero non si hanno dati; per il placeholder iniziale inserire la stringa "Caricamento dati..." sia nella lista parcheggi che nella lista delle biciclette condivise.
