### ISSUE TITLE
Comportamento non omogeneo

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.viaggia#12]
Ho perso un pò di tempo a capire che selezionando un parcheggio bisogna poi cliccare sull'icona mappa in alto nella title bar per proseguire nella funzionalità

Negli altri casi di interezione provati (accesso a una tratta di treno o autobus) "succede" sempre qualcosa al click di un elemento

La non omogeneità nei parcheggi mi ha spiazzato.

**Comment by paolaR** [comment]
Per uniformare il comportamento una soluzione è mantenere il pulsante tondo in action bar che manda alla mappa, come nelle funzionalità autobus e treni, e modificare il comportamento al tap sulla scheda. 
Con un tap sulla scheda aprire la mappa in auto zoom sul parcheggio selezionato, visualizzando il popup, nel quale oltre alle info sul parcheggio e al pulsante "indicazioni stradali" mostro il pulsante bookmark. 
Il medesimo comportamento per la funzionalità bici condivise. 
Modifica da discutere.

**Comment by paolaR** [comment]
Confermata la soluzione proposta nel commento precedente. Di seguito la rappresentazione grafica

![issue 12](https://cloud.githubusercontent.com/assets/6916472/12822382/1754bece-cb68-11e5-98c4-2cec6438c8e4.png)

**Comment by zaccog** [comment]
Nel dettaglio dei parcheggi non viene visualizzato l'indirizzo

**Comment by chin8** [comment]
non posso fare preferito di un parcheggio se entro dal dettaglio di un singolo
