### ISSUE TITLE
Pagina pianifica viaggio

### ISSUE THREAD

**Issue by paolaR** [smartcommunitylab/sco.viaggia#19]
Mantenere le opzioni di preferenza di viaggio sempre visibili.
Togliere ombreggiatura sotto i pulsanti selezionati.
Aggiungere il bottone "x" per cancellare l'indirizzo, che potrebbe essere molto lungo
Impostare la vibrazione con tap sulla mappa per cogliere un POI
Sistemare allineamenti degli elementi dei popup di inserimento ora e data.

![pianifica](https://cloud.githubusercontent.com/assets/6916472/11369416/14969d1a-92bf-11e5-94ae-55046821c976.png)

**Comment by paolaR** [comment]
La stringa dell'indirizzo è tagliata, riusciamo a gestire la stringa su due righe se la lunghezza lo necessita?

I pulsanti mappa e preferiti sono troppo attaccati tra di loro, cerchiamo una via di mezzo tra com'era prima (occupavano troppo spazio) e com'è ora.

**Comment by oskarnrk** [comment]
Essendo un input non si puo' mettere su piu linee. Come da accordi con Paola messo l'ellipsis (i puntini) se il field non e' focus, altrimenti se lo e' spariscono per poter editare.
I pulsanti sono stati distanziati.
