### ISSUE TITLE
Titolo action bar pagine 

### ISSUE THREAD

**Issue by paolaR** [smartcommunitylab/sco.viaggia#2]
Nelle pagine degli orari di Autobus Urbani, Autobus Extraurbani e Treni aggiungere la stringa "Linea" davanti al numero o alla lettera o alle destinazioni.

**Comment by pistore** [comment]
Valutare se mettere anche il nome della linea: Linea 5 non basta, visto 
che ce ne sono 2: Trento -> Povo e Povo -> Trento.
