### ISSUE TITLE
Crash app 

### ISSUE THREAD

**Issue by paolaR** [smartcommunitylab/sco.viaggia#36]
Pianifico un viaggio e rimango per alcuni minuti sulla schermata delle soluzioni, lo schermo va in sospensione e quando lo riattivo e cerco di interagire con l'app questo è il risultato: 
![crash](https://cloud.githubusercontent.com/assets/6916472/11437729/5a40ff58-94f0-11e5-9769-f3fbf1e49ee4.png)

**Comment by chin8** [comment]
Difficile da duplicare, non sempre lo fa su Android

**Comment by oskarnrk** [comment]
Perde il contesto?

**Comment by chin8** [comment]
Da verificare se dopo la modifica sui parcheggi (gestione errata dello step )  ora funziona
