### ISSUE TITLE
Tempo di parcheggio non chiaro

### ISSUE THREAD

**Issue by pistore** [smartcommunitylab/sco.viaggia#54]
Il significato della clessidra come tempo per trovare parcjeggio non e' necessariamente auto-esplicativo. 
Mettere una label (es. "Trova parcheggio") nel dettaglio del viaggio?
![image](https://cloud.githubusercontent.com/assets/4172147/11453078/85e99300-95fd-11e5-882f-8b306e1456ec.png)

Il tempo di parcheggio va sistemato anche nel fumetto sulla mappa: andrebbe spostato all'arrivo e il signififato andrebbe reso piu' comprensibile:
![image](https://cloud.githubusercontent.com/assets/4172147/11453083/a54ee8e4-95fd-11e5-975b-0429ece076ac.png)

**Comment by kazhamiakin** [comment]
Added a message. However, to move the parking info to the arrival yet to be done.

**Comment by zaccog** [comment]
String exceed screen limits

![screenshot_20160209-182304](https://cloud.githubusercontent.com/assets/4171518/12942398/16920db2-cfdb-11e5-9629-bd5dbf0424d6.png)

**Comment by chin8** [comment]
text is contained inside the cell
