### ISSUE TITLE
Testo sovrapposto in lista bici e parcheggi

### ISSUE THREAD

**Issue by regolo85** [smartcommunitylab/sco.viaggia#57]
Nelle liste delle bici e dei parcheggi il testo nelle varie card appare sovrapposto.
(su S2 con android 4.1.2)
![screenshot_2015-11-29-12-33-12](https://cloud.githubusercontent.com/assets/5494938/11456971/5060e974-969b-11e5-82f0-cc351d187c64.png)

**Comment by zaccog** [comment]
Su Samsung Galaxy S2 e HTC One S il padding non è ancora ragionevole
