### ISSUE TITLE
typo issue while saving favorites

### ISSUE THREAD

**Issue by nawaz2013** [smartcommunitylab/sco.viaggia#63]
Descr: 
- 'wann' typo

![screenshot_2015-12-03-18-37-15](https://cloud.githubusercontent.com/assets/4034293/11568937/51ef94d2-99ef-11e5-9804-78aa0df4000e.png)

**Comment by chin8** [comment]
Is it better 'Would you like to add this address in your favorites?' or 'Do you want to add this address in your favorites?'

**Comment by nawaz2013** [comment]
i think that its better to have it like.

"Do you want to add this address in your favorites?"
