### ISSUE TITLE
Pulsanti popup non tradotti

### ISSUE THREAD

**Issue by paolaR** [smartcommunitylab/sco.viaggia#64]
Nel popup di salvataggio di un itinerario, i pulsanti non sono tradotti in inglese. 
![img_0001](https://cloud.githubusercontent.com/assets/6916472/12093272/450dd374-b302-11e5-9b19-b38744fbda63.PNG)

**Comment by chin8** [comment]
questo bug non si applica alla versione cross platform ma alla versione nativa (Android)
