### ISSUE TITLE
Cableway icon + english string in italian version

### ISSUE THREAD

**Issue by zaccog** [smartcommunitylab/sco.viaggia#65]
The cableway (funivia) icon should be used instead of the bus icon when the planned trip involves the cableway.

Besides, in the second screenshot, "parking isle" is used instead of the equivalent italian string. 

![screenshot_2016-01-06-11-21-56](https://cloud.githubusercontent.com/assets/4171518/12166293/342a4748-b525-11e5-88b3-2bf892b9b57a.png)

![screenshot_2016-01-06-11-56-12](https://cloud.githubusercontent.com/assets/4171518/12166299/39e2b8d2-b525-11e5-9335-f352b2d3662c.png)

**Comment by chin8** [comment]
questo bug non si applica alla versione cross platform ma alla versione nativa (Android)
