### ISSUE TITLE
Default zoom level of path geometry

### ISSUE THREAD

**Issue by nawaz2013** [smartcommunitylab/sco.viaggia#7]
Envrionment:
Android 4.1.2

Descr:
Default zoom level is inappropriate as can be seen in image

![png4](https://cloud.githubusercontent.com/assets/4034293/11338106/6920342c-91f2-11e5-8883-ae4a044b63ee.png)

**Comment by chin8** [comment]
On my device (Android 4.1.2) the new version doesn't have the same problem

**Comment by nawaz2013** [comment]
Now it is fine. Marking it as closed.
