### ISSUE TITLE
tabella orari problemi performance

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/sco.viaggia#9]
Testato su tablet lenovo A8 (android 4.4.2)

Visualizzando le tabelle degli orari di autobus ricchi di fermate ( numero 3 e 4 ad esempio) ho avuto seri problemi di risposta, scroll sia verticale che orizzontale bloccato per parecchio tempo senza alcun feedback.

Provando con una tabella più light (tipo l'orario delle funivia) la risposta agli scroll è stata normale

**Comment by paolaR** [comment]
Nuova tabella orari da problemi con la visualizzazione del background a colonne (grigie-bianche); su iPhone le colonne sono più strette degli orari, su Samsung s2 parti del background sono grigie e altre bianche senza rispettare le colonne mentre su Huawei la dimensione delle colonne grigie non è fissa.
